### PR TITLE
add Windows support 

### LINKED ISSUE #11: Repo doesn't work on Windows
Thanks for the great repo! For a couple of reasons, this repo doesn't work on Windows. 

First reason: `make` not generally available on Windows, so [this](https://github.com/levyfan/sentencepiece-jni/blob/master/pom.xml#L59-L63) fails to build. This can be replaced by native `cmake install` per [here](https://github.com/google/sentencepiece/blob/master/test.bat#L14).

Second reason: Sentencepiece cannot link shared libraries on Windows, so this will need to be conditionally changed (see [here](https://github.com/google/sentencepiece/blob/master/test.bat#L13) in the [CMakeLists](https://github.com/levyfan/sentencepiece-jni/blob/master/src/main/native/CMakeLists.txt#L20-L21) file.

There may be some other small issues, but these are the big blockers.

### PR DESCRIPTION
**Pull request by erip**
This PR seeks to add Windows support to this repo to close #11. As a part of this, it will transition to GitHub Actions for ease of testing.

### CODE REVIEW

**Comment by erip** [comment]
@levyfan CI passes [here](https://github.com/erip/sentencepiece-jni/runs/1663640716). If you want to accept this, you can add GitHub Actions support for your repo and it should guarantee the three major platforms are supported.

**Comment by erip** [comment]
And, as an aside, this PR could probably be cleaned up by someone who knows Maven better than me. 😄 But this works and isn't too invasive.

**Review by levyfan — COMMENTED** [review]
Thank you @erip for your great work! 

One question, can we remove the file `windows-jni/include/jni.h`?

**Comment by erip** [comment]
I can try, but I suspect there may be issues. Specifically on Windows, jint is an alias to a native long, which causes a lot of issues.

**Comment by erip** [comment]
@levyfan, as I suspected this won't work: https://github.com/erip/sentencepiece-jni/runs/1668614105?check_suite_focus=true#step:4:3561

Because a `jint` is a `long` on Windows, we can't rely on the Windows JNI. The workaround with the `windows-jni/` here is the same approach we took on adding Java runtime support to PyTorch on Windows, so there's some precedent. 😅

**Pull request merged**
